#############
## this will install the sas repository mirror on the stateful host

---
- hosts: stateful
  become: yes
  become_user: root
  

  tasks:

  - name: Download mirror
    shell: |
      set -e
      mkdir -p /opt/sas/mirror
      chmod a+r /opt/sas/mirror
      # lowercase initial s, remove trailing slash if it exists
      DM=$(echo -n {{S3MirrorLocation}} | sed "s/^S/s/" | sed "s+/$++" )
      aws --region {{AWSRegion}} s3 sync ${DM} /opt/sas/mirror
      # set selinux permissions
      chcon -R -t httpd_sys_content_t /opt/sas/mirror


  - name: install httpd
    yum: name=httpd

  - name: set httpd port to 8008
    replace:
      dest: /etc/httpd/conf/httpd.conf
      regexp:  'Listen.*'
      replace: 'Listen 8008'

  - name: configure httpd
    blockinfile:
      dest: /etc/httpd/conf.d/repo.conf
      create: yes
      marker: '# {mark} sas mirror repo'
      block: |
        <Directory "/opt/sas/mirror/">
          Options All
          AllowOverride All
          Require all granted
          Satisfy any
        </Directory>
        Alias "/repo_mirror" "/opt/sas/mirror/"

  - name: start httpd
    service:
      name: httpd
      enabled: yes
      state: started
